/*
 * oled2864.c
 *
 *  Created on: 2017Äê4ÔÂ7ÈÕ
 *      Author: Administrator
 */
#include "ad_i2c.h"
#include "WordStock.h"
#include "platform_devices.h"
#include "stdio.h"
#include "stdlib.h"
#include  "oled2864.h"

void Writec(unsigned char DATA){
        uint8_t buf[2]={0x00,0x00};
        buf[1] = DATA;
        i2c_device dev;
        dev = ad_i2c_open(OLED2864);
        ad_i2c_write(dev, buf, 2);
        ad_i2c_close(dev);
}

void Writed(unsigned char DATA){
        uint8_t buf[2]={0x40,0x40};
        buf[1] = DATA;
        i2c_device dev;
        dev = ad_i2c_open(OLED2864);
        ad_i2c_write(dev, buf, 2);
        ad_i2c_close(dev);
}



void SSD1306()
{
     Writec(0xAE);//display off
     Writec(0x00);//set lower column address
     Writec(0x10);//set higher column address
     Writec(0x40);//set display start line
     Writec(0xB0);//set page address
     Writec(0x81);//set contract control
     Writec(0xCF);// VCC Generated by Internal DC/DC Circuit
     Writec(0xA1);//set segment remap  column address 127 is mapped to SEG0
     Writec(0xA6);//normal / reverse   normal display
     Writec(0xA8);//multiplex ratio
     Writec(0x3F);//1/64
     Writec(0xC8);//Com scan direction remapped mode. Scan from COM[N-1] to COM0
     Writec(0xD3);//set display offset
     Writec(0x00);
     Writec(0xD5);//set osc division
     Writec(0x80);
     Writec(0xD9);//set pre-charge period
     Writec(0x11);
     Writec(0xDa);//set COM pins
     Writec(0x12);
     Writec(0x8d);/*set charge pump enable*/
     Writec(0x14);
     Writec(0xdb);//Set VcomH
     Writec(0x20);
     Writec(0xAF);//display ON
}


//The OLED screen clearing
void fill(unsigned char dat)
{
     unsigned char i,j;
     Writec(0x00);//set lower column address
     Writec(0x10);//set higher column address
     Writec(0xB0);//set page address
     for(j = 0; j < 8; j++)
     {
         Writec(0xB0 + j);//set page address
         Writec(0x00);//set lower column address
         Writec(0x10);//set higher column address
        for(i = 0; i < 128; i++)
        {
            Writed(dat);
        }
     }
}
/*
void fill(uint8_t x,uint8_t y,unsigned char dat)
{
     unsigned char i,j;
     for(j = 0; j < 2; j++)
     {
         Writec(0xB0 + y);//set page address
         Writec(0x00 + (x/2) + (x%2) * (0x08));//set lower column address
         Writec(0x10 + (x/2) + (x%2) * (0x08));//set higher column address
                 y++;
                 if(x == 9){
                         for(i = 0; i < 49; i++)
              {
                 Writed(dat);
              }
                 }else if(x == 5){
                         for(i = 0; i < 33; i++)
              {
                 Writed(dat);
              }
                 }else if(x == 12){
                         for(i = 0; i < 24; i++)
              {
                 Writed(dat);
              }
                 }else if(x == 0){
                         for(i = 0; i < 128; i++)
              {
                 Writed(dat);
              }
                 }

     }
}
*/
//#ifdef ARDUINO_ARCH_ARC32
//On the OLED display

void show(uint8_t x, uint8_t y, uint8_t DATA)
{
    unsigned int i,j;
        for(j = 0; j < 2; j++)
        {
                Writec(0xB0 + y);//set page address
        Writec(0x00 + (x/2) + (x%2) * (0x08));//set lower column address
        Writec(0x10 + (x/2) + (x%2) * (0x08));//set higher column address
                y++;
                for(i = 0; i < 8; i++)
            {
                   Writed(WordStock[DATA][j * 8 + i]);
            }
    }
}
//#else
/*
void show(uint8_t x, uint8_t y, uint8_t DATA)
{
    unsigned char WordStock[16];
        register char b;
      for(b = 0; b < 16; b++)
                {
                        WordStock[b] = pgm_read_byte(&F8X16[DATA][b]);
                }
    unsigned int i,j;
        for(j = 0; j < 2; j++)
        {
                Writec(0xB0 + y);//set page address
        Writec(0x00 + (x/2) + (x%2) * (0x08));//set lower column address
        Writec(0x10 + (x/2) + (x%2) * (0x08));//set higher column address
                y++;
                for(i = 0; i < 8; i++)
            {
                   Writed(WordStock[j * 8 + i]);
            }
    }
}
#endif
*/
void setCursor(uint8_t x, uint8_t y)
{
        Writec(0xB0 + y);//set page address
    Writec(0x00 + (x/2) + (x%2) * (0x08));//set lower column address
    Writec(0x10 + (x/2) + (x%2) * (0x08));//set higher column address
}
/*
void print(uint8_t x, uint8_t y,float f)
{
        char buf[25];
        char *uint = buf;
        sprintf(buf,"%f",f);
        while (*uint != '\0') {
      show(x++,y,(*uint++)-' ');
    }
}
*/
void oled_print_int(uint8_t x, uint8_t y,int n)
{
        char buf[25];
        char *uint = buf;
        itoa(n,buf,10);
        while (*uint != '\0') {
      show(x++,y,(*uint++)-' ');
    }
}

void oled_print(uint8_t x, uint8_t y, const char *str)
{
    while (*str != '\0') {
        show(x++,y,(*str++)-' ');
    }
}

void oled_init(){
        SSD1306();
        fill(0x00);
}
void oled_begin()
{
        //fill(0xFF);
        //OS_DELAY(1000);
        //fill(0x00);
        oled_print(0,0,"Hello Word!");
        oled_print(0,2,"Hello Word!");
        oled_print(0,4,"Hello Word!");
        oled_print(0,6,"Hello Word!");
}

